openapi: 3.0.0
info:
  title: Eden API
  description: Methods for interacting with the Eden API
  version: 0.1.0
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.eden.art
    description: Production server

paths:
  /user/api-keys:
    get:
      description: Get all of your API keys
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiKey'
    post:
      description: Create a new API key
      requestBody:
        description: The API key to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiKey'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKey'
  /user/api-keys/{apiKey}:
    delete:
      description: Delete an API key
      parameters:
        - name: apiKey
          in: path
          description: The API key to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content